# Generated by Django 6.0.6 on 2026-06-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
