# Generated by Django 6.0.6 on 2026-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="id",
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
